version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: sample-blog
    # NOTE: Comment out 'command' when delve not use
    command: bash -c "air -c air.conf"
    stdin_open: true
    tty: true
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "3456:3456"
    depends_on:
      - db

  db:
    image: mysql:8.0
    platform: linux/x86_64
    env_file:
      - .env
    container_name: sample-blog-db
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: sample_blog
    ports:
      - "3306:3306"
    volumes:
      - ${DOCKER_DB_DATA_PATH:-./tmp/data/db}:/var/lib/mysql:cached
