version: 2.1

orbs:
  go: circleci/go@1.7.1

commands:
  setup:
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - run:
          name: "staticcheck download"
          command: |
            go install honnef.co/go/tools/cmd/staticcheck@latest
      - go/save-cache

jobs:
  staticcheck:
    docker:
      - image: cimg/go:1.17.7
    steps:
      - setup
      - run:
          name: "staticcheck"
          command: staticcheck
  tests:
    docker:
      - image: cimg/go:1.17.7
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
          MYSQL_DATABASE: sample_blog_test
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    steps:
      - setup
      - go/test:
          covermode: atomic
          failfast: true
          race: true

workflows:
  run_tests:
    jobs:
      - staticcheck
      - tests
